---
version: "2"
plugins:
  # https://docs.codeclimate.com/docs/duplication
  duplication:
    enabled: true
    config:
      languages:
        - php:

  # https://docs.codeclimate.com/docs/fixme
  fixme:
    enabled: true

  # https://docs.codeclimate.com/docs/phpcodesniffer
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"

  # https://docs.codeclimate.com/docs/phpmd
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php

  # https://docs.codeclimate.com/docs/sonar-php
  sonar-php:
    enabled: true

  # https://docs.codeclimate.com/docs/phan
  phan:
    enabled: true
    config:
      file_extensions: "php"

exclude_patterns:
  - "bootstrap/"
  - "config/"
  - "database/"
  - "public/"
  - "resources/"
  - "routes/"
  - "storage/"
  - "tests/"
  - "**/vendor/"
  - "**/node_modules/"
  - "**.md"
  - "**.json"
  - "**.xml"
  - "composer.phar"
  - "**/.DS_Store"
